### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by jazzman31** [witte/Eq#7]
Hi, 
I just looked on your files and found two issues. 
**1.** EqProcessor.h line 63: std::atomic<bool> frequenciesCurveChanged = false; //-> error: Copying member subobject of type 'std::atomic<bool>' invokes deleted constructor
**2.**  SpectrumAnalyzer.cpp line 176 - 177//-> error: No member named 'nextFFTBlockReady' in 'EqAudioProcessor'

**Comment by witte** [comment]
Hey, thanks for letting me know,

Sounds like you had a higher compiler warning level than I had up until now. Could you clone the repo again from scratch and see if it works for you? I've addressed a lot of compiler warnings on Windows, and this one about `std::atomic`'s constructor specifically [here](https://github.com/witte/Eq/commit/2555da1d4675d9ab548241d09c149b8aa026e51c).

**Comment by witte** [comment]
Ok, feel free to reopen the issue if you're still having problems. 👍
